version: "2"

linters:
  default: none
  enable:
    - unused
    - revive
    - bodyclose
    - gocritic
    - errorlint
    - nolintlint
    - misspell
    - gochecknoinits
    - exhaustive
    - decorder
    - embeddedstructfieldcheck
    - recvcheck
    - interfacebloat
  exclusions:
    rules:
      - path: (^|.*/)config\.go$
        linters:
          - revive
        text: "don't use ALL_CAPS in Go names; use CamelCase"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
